### ISSUE TITLE
error compile on latest openssl/kernel

### ISSUE THREAD

**Issue by snak81** [glftpd/socks5#5]
CentOS Linux release 8.1.1911 (Core)

[socks5]$ make clean linux

Clean succesful
g++ -c -W -Wall -g -I/usr/local/ssl/include -Iinclude src/socks5.cc -o src/socks5.o
src/socks5.cc: In member function ‘void CSockThread::mainloop()’:
src/socks5.cc:338:4: error: ‘memset’ was not declared in this scope
    memset(buffer,'\0',config.buffersize);
    ^~~~~~
src/socks5.cc:338:4: note: ‘memset’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
src/socks5.cc:7:1:
+#include <cstring>

src/socks5.cc:338:4:
    memset(buffer,'\0',config.buffersize);
    ^~~~~~
src/socks5.cc:687:8: error: ‘memcpy’ was not declared in this scope
        memcpy(&myaddr.sin_addr.s_addr,buffer+4,4);
        ^~~~~~
src/socks5.cc:687:8: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
src/socks5.cc:702:8: error: ‘memcpy’ was not declared in this scope
        memcpy(&myaddr.sin_port,buffer+buffer[4]+5,2);
        ^~~~~~
src/socks5.cc:702:8: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
src/socks5.cc:829:7: error: ‘strcpy’ was not declared in this scope
       strcpy(ifa.ifr_name,config.listen_interface.c_str());
       ^~~~~~
src/socks5.cc:829:7: note: ‘strcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
src/socks5.cc:854:7: error: ‘memcpy’ was not declared in this scope
       memcpy(buffer+8,&listenadr.sin_port,2);
       ^~~~~~
src/socks5.cc:854:7: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
src/socks5.cc:871:7: error: ‘memcpy’ was not declared in this scope
       memcpy(buffer+8,&listenadr.sin_port,2);
       ^~~~~~
src/socks5.cc:871:7: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
src/socks5.cc: In function ‘int main(int, char**)’:
src/socks5.cc:1047:3: error: ‘memset’ was not declared in this scope
   memset(k, 0,bk.length());
   ^~~~~~
src/socks5.cc:1047:3: note: ‘memset’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
src/socks5.cc: At global scope:
src/socks5.cc:86:13: warning: ‘void dyn_destroy_function(CRYPTO_dynlock_value*, const char*, int)’ defined but not used [-Wunused-function]
 static void dyn_destroy_function(struct CRYPTO_dynlock_value *l, const char *file, int line)
             ^~~~~~~~~~~~~~~~~~~~
src/socks5.cc:72:13: warning: ‘void dyn_lock_function(int, CRYPTO_dynlock_value*, const char*, int)’ defined but not used [-Wunused-function]
 static void dyn_lock_function(int mode, struct CRYPTO_dynlock_value *l, const char *file, int line)
             ^~~~~~~~~~~~~~~~~
src/socks5.cc:58:38: warning: ‘CRYPTO_dynlock_value* dyn_create_function(const char*, int)’ defined but not used [-Wunused-function]
 static struct CRYPTO_dynlock_value * dyn_create_function(const char *file, int line)
                                      ^~~~~~~~~~~~~~~~~~~
src/socks5.cc:53:22: warning: ‘long unsigned int id_function()’ defined but not used [-Wunused-function]
 static unsigned long id_function(void)
                      ^~~~~~~~~~~
src/socks5.cc:39:13: warning: ‘void locking_function(int, int, const char*, int)’ defined but not used [-Wunused-function]
 static void locking_function(int mode, int n, const char * file, int line)
             ^~~~~~~~~~~~~~~~
make: *** [Makefile:4: src/socks5.o] Error 1

**Comment by cdst** [comment]
with the above error fixed (adding a bunch of #includes in the right files) it still fails to compile due to changes in openssl

OpenSSL> version
OpenSSL 1.1.1c FIPS  28 May 2019

src/tools.cc: In function ‘int decrypt(std::__cxx11::string, unsigned char*, unsigned char*, int)’:
src/tools.cc:2089:23: error: cannot convert ‘EVP_CIPHER_CTX**’ {aka ‘evp_cipher_ctx_st**’} to ‘EVP_CIPHER_CTX*’ {aka ‘evp_cipher_ctx_st*’}
     EVP_CipherInit_ex(&ctx, EVP_bf_cfb(), NULL, NULL, NULL,ipos );
                       ^~~~
In file included from /usr/include/openssl/x509.h:18,
                 from /usr/include/openssl/ssl.h:20,
                 from include/global.h:8,
                 from include/tools.h:4,
                 from src/tools.cc:1:
/usr/include/openssl/evp.h:605:50: note:   initializing argument 1 of ‘int EVP_CipherInit_ex(EVP_CIPHER_CTX*, const EVP_CIPHER*, ENGINE*, const unsigned char*, const unsigned char*, int)’
 /*__owur*/ int EVP_CipherInit_ex(EVP_CIPHER_CTX *ctx,
                                  ~~~~~~~~~~~~~~~~^~~
src/tools.cc:2090:35: error: cannot convert ‘EVP_CIPHER_CTX**’ {aka ‘evp_cipher_ctx_st**’} to ‘EVP_CIPHER_CTX*’ {aka ‘evp_cipher_ctx_st*’}
     EVP_CIPHER_CTX_set_key_length(&ctx, key.length());
                                   ^~~~
In file included from /usr/include/openssl/x509.h:18,
                 from /usr/include/openssl/ssl.h:20,
                 from include/global.h:8,
                 from include/tools.h:4,
                 from src/tools.cc:1:
/usr/include/openssl/evp.h:678:51: note:   initializing argument 1 of ‘int EVP_CIPHER_CTX_set_key_length(EVP_CIPHER_CTX*, int)’
 int EVP_CIPHER_CTX_set_key_length(EVP_CIPHER_CTX *x, int keylen);
                                   ~~~~~~~~~~~~~~~~^
src/tools.cc:2091:23: error: cannot convert ‘EVP_CIPHER_CTX**’ {aka ‘evp_cipher_ctx_st**’} to ‘EVP_CIPHER_CTX*’ {aka ‘evp_cipher_ctx_st*’}
     EVP_CipherInit_ex(&ctx, NULL, NULL,(unsigned char*)key.c_str(), ivec,ipos );
                       ^~~~
In file included from /usr/include/openssl/x509.h:18,
                 from /usr/include/openssl/ssl.h:20,
                 from include/global.h:8,
                 from include/tools.h:4,
                 from src/tools.cc:1:
/usr/include/openssl/evp.h:605:50: note:   initializing argument 1 of ‘int EVP_CipherInit_ex(EVP_CIPHER_CTX*, const EVP_CIPHER*, ENGINE*, const unsigned char*, const unsigned char*, int)’
 /*__owur*/ int EVP_CipherInit_ex(EVP_CIPHER_CTX *ctx,
                                  ~~~~~~~~~~~~~~~~^~~
src/tools.cc:2093:23: error: cannot convert ‘EVP_CIPHER_CTX**’ {aka ‘evp_cipher_ctx_st**’} to ‘EVP_CIPHER_CTX*’ {aka ‘evp_cipher_ctx_st*’}
  if(!EVP_CipherUpdate(&ctx, dataout, &outlen, datain, s))
                       ^~~~
In file included from /usr/include/openssl/x509.h:18,
                 from /usr/include/openssl/ssl.h:20,
                 from include/global.h:8,
                 from include/tools.h:4,
                 from src/tools.cc:1:
/usr/include/openssl/evp.h:609:45: note:   initializing argument 1 of ‘int EVP_CipherUpdate(EVP_CIPHER_CTX*, unsigned char*, int*, const unsigned char*, int)’
 __owur int EVP_CipherUpdate(EVP_CIPHER_CTX *ctx, unsigned char *out,
                             ~~~~~~~~~~~~~~~~^~~
src/tools.cc:2098:26: error: cannot convert ‘EVP_CIPHER_CTX**’ {aka ‘evp_cipher_ctx_st**’} to ‘EVP_CIPHER_CTX*’ {aka ‘evp_cipher_ctx_st*’}
   EVP_CIPHER_CTX_cleanup(&ctx);
                          ^~~~
/usr/include/openssl/evp.h:676:42: note:   initializing argument 1 of ‘int EVP_CIPHER_CTX_reset(EVP_CIPHER_CTX*)’
 int EVP_CIPHER_CTX_reset(EVP_CIPHER_CTX *c);
                          ~~~~~~~~~~~~~~~~^
src/tools.cc: In function ‘int encrypt(std::__cxx11::string, unsigned char*, unsigned char*, int)’:
src/tools.cc:2110:17: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
  EVP_CIPHER_CTX ctx;
                 ^~~
src/tools.cc: In function ‘std::__cxx11::string hash(std::__cxx11::string, std::__cxx11::string)’:
src/tools.cc:2326:13: error: aggregate ‘EVP_MD_CTX mdctx’ has incomplete type and cannot be defined
  EVP_MD_CTX mdctx;
             ^~~~~
src/tools.cc:2341:5: error: ‘EVP_MD_CTX_cleanup’ was not declared in this scope
     EVP_MD_CTX_cleanup(&mdctx);
     ^~~~~~~~~~~~~~~~~~
src/tools.cc:2341:5: note: suggested alternative: ‘EVP_MD_CTX_create’
     EVP_MD_CTX_cleanup(&mdctx);
     ^~~~~~~~~~~~~~~~~~
     EVP_MD_CTX_create
src/tools.cc: In function ‘int filehash(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string&)’:
src/tools.cc:2356:13: error: aggregate ‘EVP_MD_CTX mdctx’ has incomplete type and cannot be defined
  EVP_MD_CTX mdctx;
             ^~~~~
src/tools.cc:2370:5: error: ‘EVP_MD_CTX_cleanup’ was not declared in this scope
     EVP_MD_CTX_cleanup(&mdctx);
     ^~~~~~~~~~~~~~~~~~
src/tools.cc:2370:5: note: suggested alternative: ‘EVP_MD_CTX_create’
     EVP_MD_CTX_cleanup(&mdctx);
     ^~~~~~~~~~~~~~~~~~
     EVP_MD_CTX_create
make: *** [Makefile:4: src/tools.o] Error 1

**Comment by snak81** [comment]
yes it is related of new openssl

**Comment by glftpd** [comment]
that doesnt make much sense. the version here in git compiles with new openssl just fine. Where did you get your sources ? Make sure you are using the latest.

**Comment by cdst** [comment]
Seems I had an old version - pre 1.1 SSL fix. With the source taken from gh it compiled fine. I guess this issue can be closed.
